language: node_js 
node_js: stable

cache:
  directories:
    - node_modules

install: 
  - npm install

before_script:
  - git config user.name "tt"
  - git config user.email "96486d9b@gmail.com"
  - sed -i'' "s~https://github.com/ttcqaq/blog.git~https://${GITHUB_TOKEN}@github.com/ttcqaq/blog.git~" _config.yml

script: 
  - hexo g
  - gulp
  - hexo d

branches: 
  only: 
    - master


