name: hexo-blog

on:
  push:
    branches: master

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g
        gulp
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./public
    # - name: Deploy to Github Pages
    #   env:
    #     GIT_NAME: antct
    #     GIT_EMAIL: 527892245@qq.com
    #     REPO: github.com/antct/blog
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #   run: |
    #     git config --global user.name $GI
    #     git config --global user.email $GIT_EMAIL
    #     sed -i'' "s~https://${REPO}.git~https://${GIT_NAME}:${ACCESS_TOKEN}@${REPO}.git~" _config.yml
    #     hexo d
